### PR TITLE
add rtl support

### PR DESCRIPTION
**Pull request by ariaieboy**
Hi
I tried to add RTL support to your library.
To use RTL mode, users must add `dir='rtl'` to their HTML tag.

### CODE REVIEW

**Comment by CodeWithDennis** [comment]
@dipson88 Any news on this?

**Review by mszabeh — COMMENTED** [review]
add rtl support

**Review by mszabeh — APPROVED** [review]

**Comment by mszabeh** [comment]
Hi, @ariaieboy , @dipson88 
when this PR will be completed?

**Comment by dipson88** [comment]
Hi, I will check this PR on the next week.

**Comment by dipson88** [comment]
Was updated in v0.10.0. https://github.com/dipson88/treeselectjs/pull/85
Thank you for your PR @ariaieboy, I moved your code into my PR and updated a couple of things.

**Pull request closed without merging**
